[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc", "libsndfile"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python -m gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 server:app"