providers = ["python"]

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc", "libsndfile"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 server:app"