[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coqui-tts-server"
version = "1.0.0"
dependencies = [
    "flask==3.0.0",
    "gunicorn==21.2.0",
    "TTS==0.22.0"
]